#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers
echo "
listen load balancer
bind *:80
mode http
balance roundrobin
option httpclose
option forwardfor
server 76173-web-01 52.91.118.28 check
server 76173-web-02 52.91.156.190 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
